version: '3.8'

services:
  api:
    build: .
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db
    ports:
      - 8001:5432

volumes:
  postgres_data:

